language: java
node_js: stable
jdk:
- oraclejdk8
addons:
  ssh_known_hosts: ${DEPLOY_HOST}
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_2170a53262f2_key -iv $encrypted_2170a53262f2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- (cd webui && npm install)
- mvn install -DskipTests=true -Dmaven.javadoc.skip=trueh
script:
- (cd webui && node_modules/@angular/cli/bin/ng build --prod --aot=true)
- mvn install
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" target/xbirthdays-1.0.0.jar xhinliang@${DEPLOY_HOST}:/home/xhinliang/app/birthdays/
  on:
    branch: master
